# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look at https://github.com/robbyrussell/oh-my-zsh/wiki/themes for alternatives
ZSH_THEME="robbyrussell"
RPS1='[$(ruby_prompt_info)]$EPS1'  # Add ruby version on prompt (float right)

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(rake colored-man-pages rand-quote gitfast themes bundler brew rbenv last-working-dir common-aliases sublime history-substring-search zsh-syntax-highlighting)

# Oh-my-ZSH config loading.
source $ZSH/oh-my-zsh.sh

# Resets PATH - just in case.
export PATH='/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games'

# Disable zsh correction
unsetopt correct_all

# To use Homebrew's directories rather than ~/.rbenv
export RBENV_ROOT=$HOME/.rbenv

# Adding rbenv path to the PATH so Ruby works correctly.
export PATH="${RBENV_ROOT}/shims:${RBENV_ROOT}/bin:${PATH}"

# Adding icu4c path to the PATH for postgres
export PATH="/usr/local/opt/icu4c/bin:/usr/local/opt/icu4c/sbin:${PATH}"

# Disables unbreakable sapces.
# setxkbmap -option "nbsp:none"

# Gather handy aliases
[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"

# UTF-8 is our default encoding
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Bundle editor
export BUNDLER_EDITOR="vim"

# Set tmux as terminal.
if command -v tmux>/dev/null; then
  tmux ls | grep -vq attached && TMUXARG="attach-session -d"
  [[ ! $TERM =~ screen ]] && [ -z $TMUX ] && exec eval "tmux -2 $TMUXARG"
fi

alias todo=todo.sh

source ~/.quicklaunch.sh
